### ISSUE TITLE
ADT.dll

### ISSUE THREAD

**Issue by pjlammertyn** [pjlammertyn/work#28]
-eDialyse
-eFacturation
-eZHH
-MPC

**Comment by fvanderhaegen** [comment]
-eCathlab gedaan

**Comment by pjlammertyn** [comment]
gedaan:
-eBed MVC
-XTenso Rest
-SMS Broker
-eCardio Web
-ITrans
-ePatlan

**Comment by fvanderhaegen** [comment]
-MPC gedaan
